spring.application.name=Adaptive-API-Rate-Limiter
rate.limiter.capacity=10
rate.limiter.refill-rate=2.0
rate.limiter.window-duration=60000   
rate.limiter.clean-windows-required=5
rate.limiter.recovery-factor=1.1
rate.limiter.floor-percent=0.10
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
rate.limiter.ttl.hours=24
